import { Symbol } from "@date/types";

export const extract: Record<Symbol, (date: Date, pattern: string) => string> =
  {
    G: (date: Date, pattern: string): string => pattern,
    u: (date: Date, pattern: string): string => pattern,
    y: (date: Date, pattern: string): string => pattern,
    D: (date: Date, pattern: string): string => pattern,
    "M/L": (date: Date, pattern: string): string => pattern,
    d: (date: Date, pattern: string): string => pattern,
    "Q/q": (date: Date, pattern: string): string => pattern,
    Y: (date: Date, pattern: string): string => pattern,
    w: (date: Date, pattern: string): string => pattern,
    W: (date: Date, pattern: string): string => pattern,
    E: (date: Date, pattern: string): string => pattern,
    "e/c": (date: Date, pattern: string): string => pattern,
    F: (date: Date, pattern: string): string => pattern,
    a: (date: Date, pattern: string): string => pattern,
    h: (date: Date, pattern: string): string => pattern,
    K: (date: Date, pattern: string): string => pattern,
    k: (date: Date, pattern: string): string => pattern,
    H: (date: Date, pattern: string): string => pattern,
    m: (date: Date, pattern: string): string => pattern,
    s: (date: Date, pattern: string): string => pattern,
    S: (date: Date, pattern: string): string => pattern,
    A: (date: Date, pattern: string): string => pattern,
    n: (date: Date, pattern: string): string => pattern,
    N: (date: Date, pattern: string): string => pattern,
    V: (date: Date, pattern: string): string => pattern,
    z: (date: Date, pattern: string): string => pattern,
    O: (date: Date, pattern: string): string => pattern,
    X: (date: Date, pattern: string): string => pattern,
    x: (date: Date, pattern: string): string => pattern,
    Z: (date: Date, pattern: string): string => pattern,
    p: (date: Date, pattern: string): string => pattern,
    "'": (date: Date, pattern: string): string => pattern,
    "''": (date: Date, pattern: string): string => pattern,
    "[": (date: Date, pattern: string): string => pattern,
    "]": (date: Date, pattern: string): string => pattern,
    "#": (date: Date, pattern: string): string => pattern,
    "{": (date: Date, pattern: string): string => pattern,
    "}": (date: Date, pattern: string): string => pattern,
  };
